export const categories: {
  [key: string]: { emoji: string; items: { emoji: string; label: string }[] };
} = {
  vegetables: {
    emoji: '🥦',
    items: [
      { emoji: '🧅', label: 'onion' },
      { emoji: '🥔', label: 'potato' },
      { emoji: '🥕', label: 'carrot' },
      { emoji: '🥒', label: 'cucumber' },
      { emoji: '🌶️', label: 'pepper' },
      { emoji: '🍅', label: 'tomato' },
      { emoji: '🥦', label: 'broccoli' },
      { emoji: '🥬', label: 'cabbage' },
      { emoji: '🥬', label: 'spinach' },
      { emoji: '🥬', label: 'lettuce' },
      { emoji: '🥒', label: 'zucchini' },
      { emoji: '🍆', label: 'eggplant' },
      { emoji: '🧄', label: 'garlic' },
      { emoji: '🫚', label: 'ginger' },
      { emoji: '🍄', label: 'mushroom' },
      { emoji: '🥦', label: 'cauliflower' },
      { emoji: '🌽', label: 'corn' },
      { emoji: '🟢', label: 'peas' },
      { emoji: '🍠', label: 'sweet_potato' },
      { emoji: '🍠', label: 'beetroot' },
      { emoji: '🥬', label: 'napa_cabbage' },
      { emoji: '🌿', label: 'perilla_leaf' },
      { emoji: '🥬', label: 'korean_chives' },
      { emoji: '🥬', label: 'korean_lettuce' },
      { emoji: '🥕', label: 'radish' },
      { emoji: '🍄', label: 'shiitake_mushroom' },
      { emoji: '🍄', label: 'enoki_mushroom' },
      { emoji: '🍄', label: 'king_oyster_mushroom' },
      { emoji: '🌿', label: 'bean_sprouts' },
      { emoji: '🌿', label: 'korean_mugwort' },
      { emoji: '🌿', label: 'crown_daisy' },
      { emoji: '🥕', label: 'korean_carrot' },
      { emoji: '🌿', label: 'water_dropwort' },
      { emoji: '🥬', label: 'sesame_leaves' },
      { emoji: '🌿', label: 'chamnamul' },
      { emoji: '🌿', label: 'wild_chives' },
      { emoji: '🥒', label: 'okra' },
      { emoji: '🥒', label: 'bitter_melon' },
      { emoji: '🥬', label: 'swiss_chard' },
      { emoji: '🍄', label: 'chanterelle' },
      { emoji: '🍄', label: 'porcini' },
      { emoji: '🍄', label: 'morel' },
      { emoji: '🥬', label: 'arugula' },
      { emoji: '🌽', label: 'baby_corn' },
      { emoji: '🥕', label: 'parsnip' },
      { emoji: '🌿', label: 'dill' },
      { emoji: '🌿', label: 'cilantro' },
      { emoji: '🌶️', label: 'habanero' },
      { emoji: '🌶️', label: 'serrano' },
      { emoji: '🍠', label: 'yucca' },
      { emoji: '🥕', label: 'turnip' },
      { emoji: '🌿', label: 'fennel' },
      { emoji: '🌿', label: 'lemongrass' },
      { emoji: '🥕', label: 'baby_carrots' },
      { emoji: '🌿', label: 'basil' },
      { emoji: '🍄', label: 'white_button_mushroom' },
      { emoji: '🥬', label: 'romaine_lettuce' },
      { emoji: '🍅', label: 'cherry_tomato' },
      { emoji: '🥦', label: 'asparagus' },
      { emoji: '🌿', label: 'chicory' },
      { emoji: '🌿', label: 'endive' },
      { emoji: '🍠', label: 'salsify' },
      { emoji: '🌿', label: 'sage' },
      { emoji: '🌿', label: 'thyme' },
      { emoji: '🌿', label: 'rosemary' },
      { emoji: '🌿', label: 'oregano' },
      { emoji: '🌿', label: 'lavender' },
      { emoji: '🌿', label: 'bay_leaf' },
      { emoji: '🌿', label: 'mint' },
      { emoji: '🥒', label: 'chayote' },
      { emoji: '🌿', label: 'shiso' },
      { emoji: '🌿', label: 'marjoram' },
      { emoji: '🍠', label: 'taro' },
      { emoji: '🥬', label: 'kale' },
      { emoji: '🥒', label: 'chinese_cabbage' },
      { emoji: '🍆', label: 'indian_eggplant' },
      { emoji: '🌽', label: 'hominy' },
      { emoji: '🍄', label: 'shiitake' },
      { emoji: '🍄', label: 'maitake' },
      { emoji: '🥦', label: 'broccolini' },
      { emoji: '🌿', label: 'tarragon' },
      { emoji: '🌿', label: 'lovage' },
      { emoji: '🥒', label: 'pumpkin' },
      { emoji: '🥒', label: 'butternut_squash' },
      { emoji: '🥬', label: 'bok_choy' },
      { emoji: '🌽', label: 'baby_corn' },
      { emoji: '🥒', label: 'spaghetti_squash' },
      { emoji: '🥬', label: 'collard_greens' },
      { emoji: '🥬', label: 'mustard_greens' },
      { emoji: '🍅', label: 'heirloom_tomato' },
      { emoji: '🍅', label: 'roma_tomato' },
      { emoji: '🥬', label: 'kale' },
      { emoji: '🌽', label: 'sweet_corn' },
      // 추가된 아이템들
      { emoji: '🌿', label: 'chamnamul' },
      { emoji: '🥬', label: 'mustard_greens' },
      { emoji: '🥕', label: 'radish_sprouts' },
      { emoji: '🌿', label: 'lotus_root' },
      { emoji: '🌿', label: 'chrysanthemum' },
      { emoji: '🌿', label: 'broccoli_sprouts' },
      { emoji: '🥦', label: 'chinese_broccoli' },
      { emoji: '🥬', label: 'korean_cabbage' },
      { emoji: '🟢', label: 'edamame' },
      { emoji: '🌿', label: 'pea_shoots' },
      { emoji: '🥬', label: 'purple_sprouting_broccoli' },
      { emoji: '🥒', label: 'acorn_squash' },
      { emoji: '🍊', label: 'korean_grape' },
      { emoji: '🍊', label: 'korean_melon' },
      { emoji: '🌽', label: 'baby_corn' },
      { emoji: '🥒', label: 'spaghetti_squash' },
      { emoji: '🍎', label: 'pomegranate' },
    ],
  },
  meats: {
    emoji: '🍖',
    items: [
      { emoji: '🥩', label: 'beef' },
      { emoji: '🍗', label: 'chicken' },
      { emoji: '🥓', label: 'pork_belly' },
      { emoji: '🍖', label: 'pork_shoulder' },
      { emoji: '🍖', label: 'pork_rib' },
      { emoji: '🍖', label: 'pork_butt' },
      { emoji: '🥩', label: 'ribeye' },
      { emoji: '🥩', label: 'tenderloin' },
      { emoji: '🥩', label: 'brisket' },
      { emoji: '🥩', label: 'sirloin' },
      { emoji: '🥩', label: 'flank_steak' },
      { emoji: '🍖', label: 'short_ribs' },
      { emoji: '🍖', label: 'spare_ribs' },
      { emoji: '🍖', label: 'ham' },
      { emoji: '🌭', label: 'sausage' },
      { emoji: '🍖', label: 'bacon' },
      { emoji: '🦆', label: 'duck' },
      { emoji: '🦃', label: 'turkey' },
      { emoji: '🐐', label: 'goat' },
      { emoji: '🐇', label: 'rabbit' },
      { emoji: '🦌', label: 'venison' },
      { emoji: '🍖', label: 'salami' },
      { emoji: '🍖', label: 'prosciutto' },
      { emoji: '🍖', label: 'chorizo' },
      { emoji: '🍖', label: 'meatballs' },
      { emoji: '🥩', label: 'oxtail' },
      { emoji: '🍗', label: 'chicken_breast' },
      { emoji: '🍗', label: 'chicken_thigh' },
      { emoji: '🍗', label: 'chicken_wing' },
      { emoji: '🍖', label: 'lamb' },
      { emoji: '🍗', label: 'chicken_feet' },
      { emoji: '🍖', label: 'galbi' },
      { emoji: '🥩', label: 'veal' },
      { emoji: '🍗', label: 'quail' },
      { emoji: '🍗', label: 'pigeon' },
      { emoji: '🍖', label: 'kielbasa' },
      { emoji: '🍖', label: 'bresaola' },
      { emoji: '🍖', label: 'liver' },
      { emoji: '🍖', label: 'tripe' },
      { emoji: '🍗', label: 'giblets' },
      { emoji: '🍗', label: 'duck_breast' },
      { emoji: '🍗', label: 'pheasant' },
      { emoji: '🍗', label: 'guinea_fowl' },
      { emoji: '🍗', label: 'ostrich' },
      { emoji: '🍗', label: 'emu' },
      { emoji: '🍗', label: 'alligator' },
      { emoji: '🥩', label: 'wiener_schnitzel' },
      { emoji: '🍗', label: 'fried_chicken' },
      { emoji: '🍖', label: 'roast_beef' },
      { emoji: '🍗', label: 'buffalo_wings' },
      { emoji: '🥩', label: 'new_york_strip' },
      { emoji: '🥩', label: 'filet_mignon' },
      { emoji: '🍗', label: 'drumstick' },
      { emoji: '🥩', label: 'hanger_steak' },
      { emoji: '🥩', label: 'tri_tip' },
      { emoji: '🥩', label: 'porterhouse' },
      // 추가된 아이템들
      { emoji: '🍖', label: 'jeju_black_pork' },
      { emoji: '🍖', label: 'cheongyang_chili_pork' },
      { emoji: '🍖', label: 'duck_bulgogi' },
      { emoji: '🍖', label: 'chadolbaegi' },
      { emoji: '🍖', label: 'bulgogi' },
      { emoji: '🍖', label: 'jeyuk_bokkeum' },
      { emoji: '🍖', label: 'tteokgalbi' },
      { emoji: '🍖', label: 'soondae' },
      { emoji: '🍖', label: 'dakgalbi' },
      { emoji: '🍖', label: 'bossam' },
      { emoji: '🍖', label: 'jokbal' },
      { emoji: '🍖', label: 'blood_tofu' },
    ],
  },
  sauces: {
    emoji: '🥫',
    items: [
      { emoji: '🥢', label: 'soy_sauce' },
      { emoji: '🍅', label: 'ketchup' },
      { emoji: '🌭', label: 'mustard' },
      { emoji: '🥪', label: 'mayonnaise' },
      { emoji: '🍖', label: 'bbq_sauce' },
      { emoji: '🌶️', label: 'hot_sauce' },
      { emoji: '🌿', label: 'pesto' },
      { emoji: '🥗', label: 'ranch' },
      { emoji: '🍤', label: 'tartar_sauce' },
      { emoji: '🥢', label: 'teriyaki_sauce' },
      { emoji: '🥢', label: 'hoisin_sauce' },
      { emoji: '🐟', label: 'fish_sauce' },
      { emoji: '🌿', label: 'chimichurri' },
      { emoji: '🍯', label: 'honey' },
      { emoji: '🌶️', label: 'sriracha' },
      { emoji: '🥢', label: 'soy_paste' },
      { emoji: '🍶', label: 'vinegar' },
      { emoji: '🫒', label: 'olive_oil' },
      { emoji: '🥢', label: 'sesame_oil' },
      { emoji: '🍶', label: 'balsamic_vinegar' },
      { emoji: '🌶️', label: 'gochujang' },
      { emoji: '🥢', label: 'doenjang' },
      { emoji: '🥢', label: 'ssamjang' },
      { emoji: '🥢', label: 'soybean_paste' },
      { emoji: '🥢', label: 'chunjang' },
      { emoji: '🥢', label: 'mirin' },
      { emoji: '🥢', label: 'miso' },
      { emoji: '🥢', label: 'chojang' },
      { emoji: '🥢', label: 'myeolchi_aekjeot' },
      { emoji: '🥢', label: 'ganjang' },
      { emoji: '🥫', label: 'wasabi' },
      { emoji: '🍅', label: 'tomato_paste' },
      { emoji: '🍅', label: 'marinara' },
      { emoji: '🥢', label: 'chogochujang' },
      { emoji: '🥢', label: 'yeondu' },
      { emoji: '🥫', label: 'red_pepper_paste' },
      { emoji: '🥫', label: 'perilla_oil' },
      { emoji: '🥫', label: 'corn_syrup' },
      { emoji: '🥫', label: 'rice_syrup' },
      { emoji: '🥫', label: 'plum_extract' },
      { emoji: '🥫', label: 'ssuk' },
      { emoji: '🥫', label: 'sesame_paste' },
      { emoji: '🥫', label: 'worcestershire_sauce' },
      { emoji: '🥫', label: 'demi_glace' },
      { emoji: '🥫', label: 'tonkatsu_sauce' },
      { emoji: '🥫', label: 'ponzu' },
      { emoji: '🥫', label: 'yuzu_sauce' },
      { emoji: '🥫', label: 'buffalo_sauce' },
      { emoji: '🥫', label: 'sriracha_mayo' },
      { emoji: '🥫', label: 'honey_mustard' },
      { emoji: '🥫', label: 'blue_cheese_dressing' },
      { emoji: '🥫', label: 'caesar_dressing' },
    ],
  },
  fruits: {
    emoji: '🍎',
    items: [
      { emoji: '🍎', label: 'apple' },
      { emoji: '🍌', label: 'banana' },
      { emoji: '🍊', label: 'orange' },
      { emoji: '🍓', label: 'strawberry' },
      { emoji: '🫐', label: 'blueberry' },
      { emoji: '🍇', label: 'grape' },
      { emoji: '🍈', label: 'melon' },
      { emoji: '🍍', label: 'pineapple' },
      { emoji: '🥝', label: 'kiwi' },
      { emoji: '🥭', label: 'mango' },
      { emoji: '🍐', label: 'pear' },
      { emoji: '🍑', label: 'peach' },
      { emoji: '🍑', label: 'plum' },
      { emoji: '🍒', label: 'cherry' },
      { emoji: '🍇', label: 'fig' },
      { emoji: '🌴', label: 'date' },
      { emoji: '🍎', label: 'pomegranate' },
      { emoji: '🍑', label: 'apricot' },
      { emoji: '🫐', label: 'blackberry' },
      { emoji: '🫐', label: 'raspberry' },
      { emoji: '🍋', label: 'lemon' },
      { emoji: '🍋', label: 'lime' },
      { emoji: '🍉', label: 'watermelon' },
      { emoji: '🍈', label: 'honeydew' },
      { emoji: '🍏', label: 'green_apple' },
      { emoji: '🍊', label: 'tangerine' },
      { emoji: '🍍', label: 'papaya' },
      { emoji: '🍏', label: 'asian_pear' },
      { emoji: '🍇', label: 'korean_grape' },
      { emoji: '🍊', label: 'persimmon' },
      { emoji: '🍏', label: 'korean_melon' },
      { emoji: '🍎', label: 'cranberry' },
      { emoji: '🍊', label: 'yuzu' },
      { emoji: '🍉', label: 'cantaloupe' },
      { emoji: '🍊', label: 'blood_orange' },
      { emoji: '🍑', label: 'nectarine' },
      { emoji: '🥭', label: 'guava' },
      { emoji: '🍊', label: 'kumquat' },
      { emoji: '🍉', label: 'gac' },
      { emoji: '🍏', label: 'soursop' },
      { emoji: '🍏', label: 'cherimoya' },
      { emoji: '🍉', label: 'durian' },
      { emoji: '🍉', label: 'jackfruit' },
      { emoji: '🍊', label: 'tangelo' },
      { emoji: '🍏', label: 'star_fruit' },
      { emoji: '🍉', label: 'breadfruit' },
      { emoji: '🍉', label: 'santol' },
      { emoji: '🍏', label: 'rambutan' },
      { emoji: '🍏', label: 'langsat' },
      { emoji: '🍎', label: 'honeycrisp_apple' },
      { emoji: '🍎', label: 'granny_smith_apple' },
      { emoji: '🍎', label: 'red_delicious_apple' },
      { emoji: '🍏', label: 'black_currant' },
      { emoji: '🍊', label: 'clementine' },
    ],
  },
  dairy: {
    emoji: '🧀',
    items: [
      { emoji: '🥛', label: 'milk' },
      { emoji: '🧀', label: 'cheese' },
      { emoji: '🧈', label: 'butter' },
      { emoji: '🥛', label: 'yogurt' },
      { emoji: '🥛', label: 'cream' },
      { emoji: '🥛', label: 'sour_cream' },
      { emoji: '🧀', label: 'cream_cheese' },
      { emoji: '🍦', label: 'ice_cream' },
      { emoji: '🍦', label: 'whipped_cream' },
      { emoji: '🥛', label: 'condensed_milk' },
      { emoji: '🥛', label: 'evaporated_milk' },
      { emoji: '🧀', label: 'parmesan' },
      { emoji: '🧀', label: 'mozzarella' },
      { emoji: '🧀', label: 'brie' },
      { emoji: '🧀', label: 'cheddar' },
      { emoji: '🧀', label: 'gouda' },
      { emoji: '🧀', label: 'feta' },
      { emoji: '🧀', label: 'blue_cheese' },
      { emoji: '🧀', label: 'swiss_cheese' },
      { emoji: '🧀', label: 'provolone' },
      { emoji: '🥛', label: 'buttermilk' },
      { emoji: '🧀', label: 'ricotta' },
      { emoji: '🧀', label: 'cottage_cheese' },
      { emoji: '🥛', label: 'kefir' },
      { emoji: '🧀', label: 'mascarpone' },
      { emoji: '🧀', label: 'camembert' },
      { emoji: '🧀', label: 'gruyere' },
      { emoji: '🧀', label: 'pecorino' },
      { emoji: '🧀', label: 'emmental' },
      { emoji: '🧀', label: 'colby_jack' },
      { emoji: '🧀', label: 'monterey_jack' },
      { emoji: '🧀', label: 'pepper_jack' },
      { emoji: '🧀', label: 'havarti' },
      { emoji: '🧀', label: 'provolone' },
    ],
  },
  grains: {
    emoji: '🍞',
    items: [
      { emoji: '🍚', label: 'rice' },
      { emoji: '🍞', label: 'bread' },
      { emoji: '🍝', label: 'pasta' },
      { emoji: '🌾', label: 'oats' },
      { emoji: '🌾', label: 'quinoa' },
      { emoji: '🌾', label: 'barley' },
      { emoji: '🌽', label: 'cornmeal' },
      { emoji: '🌾', label: 'bulgur' },
      { emoji: '🌾', label: 'couscous' },
      { emoji: '🌾', label: 'wheat_flour' },
      { emoji: '🌾', label: 'rye' },
      { emoji: '🌾', label: 'buckwheat' },
      { emoji: '🌾', label: 'sorghum' },
      { emoji: '🌾', label: 'millet' },
      { emoji: '🌾', label: 'amaranth' },
      { emoji: '🌾', label: 'farro' },
      { emoji: '🌾', label: 'spelt' },
      { emoji: '🌾', label: 'teff' },
      { emoji: '🌾', label: 'kamut' },
      { emoji: '🌾', label: 'freekeh' },
      { emoji: '🌾', label: 'semolina' },
      { emoji: '🌾', label: 'rice_noodles' },
      { emoji: '🌾', label: 'udon_noodles' },
      { emoji: '🌾', label: 'soba_noodles' },
      { emoji: '🌾', label: 'ramen_noodles' },
      { emoji: '🍚', label: 'sticky_rice' },
      { emoji: '🌾', label: 'barley_tea' },
      { emoji: '🌾', label: 'corn_tea' },
      { emoji: '🍞', label: 'baguette' },
      { emoji: '🍞', label: 'brioche' },
      { emoji: '🍞', label: 'sourdough' },
      { emoji: '🍞', label: 'ciabatta' },
      { emoji: '🍞', label: 'pita' },
      { emoji: '🍚', label: 'brown_rice' },
      { emoji: '🍞', label: 'whole_grain_bread' },
      { emoji: '🍚', label: 'jasmine_rice' },
      { emoji: '🍚', label: 'basmati_rice' },
      { emoji: '🍚', label: 'wild_rice' },
      { emoji: '🍚', label: 'sushi_rice' },
      { emoji: '🍞', label: 'naan' },
      { emoji: '🍚', label: 'black_rice' },
      { emoji: '🍞', label: 'focaccia' },
      { emoji: '🍞', label: 'roti' },
      { emoji: '🍞', label: 'lavash' },
      { emoji: '🍞', label: 'chapati' },
      { emoji: '🍚', label: 'glutinous_rice' },
      { emoji: '🍞', label: 'cornbread' },
      { emoji: '🍞', label: 'bagel' },
      { emoji: '🍞', label: 'english_muffin' },
      { emoji: '🍚', label: 'polenta' },
      { emoji: '🍚', label: 'grits' },
    ],
  },
  seafood: {
    emoji: '🐟',
    items: [
      { emoji: '🐟', label: 'salmon' },
      { emoji: '🐟', label: 'tuna' },
      { emoji: '🍤', label: 'shrimp' },
      { emoji: '🦀', label: 'crab' },
      { emoji: '🦞', label: 'lobster' },
      { emoji: '🦪', label: 'oyster' },
      { emoji: '🦪', label: 'mussel' },
      { emoji: '🦪', label: 'clam' },
      { emoji: '🦪', label: 'scallop' },
      { emoji: '🐙', label: 'octopus' },
      { emoji: '🦑', label: 'squid' },
      { emoji: '🐟', label: 'anchovy' },
      { emoji: '🐟', label: 'sardine' },
      { emoji: '🐟', label: 'mackerel' },
      { emoji: '🐟', label: 'cod' },
      { emoji: '🐟', label: 'haddock' },
      { emoji: '🐟', label: 'halibut' },
      { emoji: '🐟', label: 'trout' },
      { emoji: '🐟', label: 'snapper' },
      { emoji: '🐟', label: 'sea_bass' },
      { emoji: '🐟', label: 'tilapia' },
      { emoji: '🐟', label: 'swordfish' },
      { emoji: '🐟', label: 'king_crab' },
      { emoji: '🦞', label: 'crayfish' },
      { emoji: '🐟', label: 'grouper' },
      { emoji: '🐟', label: 'dried_pollack' },
      { emoji: '🐟', label: 'myeolchi' },
      { emoji: '🐟', label: 'godeungeo' },
      { emoji: '🐟', label: 'galchi' },
      { emoji: '🐟', label: 'hongeo' },
      { emoji: '🐟', label: 'herring' },
      { emoji: '🐟', label: 'eel' },
      { emoji: '🐟', label: 'turbot' },
      { emoji: '🐟', label: 'plaice' },
      { emoji: '🐟', label: 'hoki' },
      { emoji: '🐟', label: 'abalone' },
      { emoji: '🐟', label: 'sea_cucumber' },
      { emoji: '🐟', label: 'kelp' },
      { emoji: '🐟', label: 'seaweed' },
      { emoji: '🐟', label: 'spiny_lobster' },
      { emoji: '🐟', label: 'monkfish' },
      { emoji: '🐟', label: 'pollock' },
      { emoji: '🐟', label: 'amberjack' },
      { emoji: '🐟', label: 'yellowtail' },
      { emoji: '🐟', label: 'snapper' },
      { emoji: '🐟', label: 'whiting' },
      { emoji: '🐟', label: 'skate' },
      { emoji: '🐟', label: 'king_mackerel' },
      { emoji: '🐟', label: 'conch' },
      { emoji: '🐟', label: 'catfish' },
      { emoji: '🐟', label: 'blue_crab' },
      { emoji: '🐟', label: 'rainbow_trout' },
      { emoji: '🐟', label: 'rockfish' },
      { emoji: '🐟', label: 'mahi_mahi' },
    ],
  },
};
