export const categories: { [key: string]: { emoji: string; label: string }[] } = {
  vegetables: [
    { emoji: '🧅', label: 'onion' },
    { emoji: '🥔', label: 'potato' },
    { emoji: '🥕', label: 'carrot' },
    { emoji: '🥒', label: 'cucumber' },
    { emoji: '🌶️', label: 'pepper' },
    { emoji: '🍅', label: 'tomato' },
    { emoji: '🥦', label: 'broccoli' },
    { emoji: '🥬', label: 'cabbage' },
    { emoji: '🥬', label: 'spinach' },
    { emoji: '🥬', label: 'lettuce' },
    { emoji: '🥒', label: 'zucchini' },
    { emoji: '🍆', label: 'eggplant' },
    { emoji: '🧄', label: 'garlic' },
    { emoji: '🫚', label: 'ginger' },
    { emoji: '🍄', label: 'mushroom' },
    { emoji: '🥦', label: 'cauliflower' },
    { emoji: '🌽', label: 'corn' },
    { emoji: '🟢', label: 'peas' },
    { emoji: '🍠', label: 'sweet_potato' },
    { emoji: '🍠', label: 'beetroot' },
    // Korean specific vegetables
    { emoji: '🥬', label: 'napa_cabbage' },
    { emoji: '🌿', label: 'perilla_leaf' },
    { emoji: '🥬', label: 'korean_chives' },
    { emoji: '🥬', label: 'korean_lettuce' },
    { emoji: '🥕', label: 'radish' },
    { emoji: '🍄', label: 'shiitake_mushroom' },
    { emoji: '🍄', label: 'enoki_mushroom' },
    { emoji: '🍄', label: 'king_oyster_mushroom' },
    { emoji: '🌿', label: 'bean_sprouts' },
    { emoji: '🌿', label: 'korean_mugwort' },
    { emoji: '🌿', label: 'crown_daisy' },
    { emoji: '🥦', label: 'radish_sprouts' },
    { emoji: '🍠', label: 'lotus_root' },
    { emoji: '🌽', label: 'corn_tea' },
    { emoji: '🌿', label: 'dandelion_greens' },
    { emoji: '🥬', label: 'minari' },
    { emoji: '🍠', label: 'sweet_pumpkin' },
    { emoji: '🌿', label: 'burdock' },
    { emoji: '🥬', label: 'kale' },
    { emoji: '🌿', label: 'chamnamul' },
  ],
  meats: [
    { emoji: '🥩', label: 'beef' },
    { emoji: '🍗', label: 'chicken' },
    { emoji: '🥓', label: 'pork_belly' },
    { emoji: '🍖', label: 'pork_shoulder' },
    { emoji: '🍖', label: 'pork_rib' },
    { emoji: '🍖', label: 'pork_butt' },
    { emoji: '🥩', label: 'ribeye' },
    { emoji: '🥩', label: 'tenderloin' },
    { emoji: '🥩', label: 'brisket' },
    { emoji: '🥩', label: 'sirloin' },
    { emoji: '🥩', label: 'flank_steak' },
    { emoji: '🍖', label: 'short_ribs' },
    { emoji: '🍖', label: 'spare_ribs' },
    { emoji: '🍖', label: 'ham' },
    { emoji: '🌭', label: 'sausage' },
    { emoji: '🍖', label: 'bacon' },
    { emoji: '🦆', label: 'duck' },
    { emoji: '🦃', label: 'turkey' },
    { emoji: '🐐', label: 'goat' },
    { emoji: '🐇', label: 'rabbit' },
    { emoji: '🦌', label: 'venison' },
    { emoji: '🍖', label: 'salami' },
    { emoji: '🍖', label: 'prosciutto' },
    { emoji: '🍖', label: 'chorizo' },
    { emoji: '🍖', label: 'meatballs' },
    { emoji: '🥩', label: 'oxtail' },
  ],
  sauces: [
    { emoji: '🥢', label: 'soy_sauce' },
    { emoji: '🍅', label: 'ketchup' },
    { emoji: '🌭', label: 'mustard' },
    { emoji: '🥪', label: 'mayonnaise' },
    { emoji: '🍖', label: 'bbq_sauce' },
    { emoji: '🌶️', label: 'hot_sauce' },
    { emoji: '🌿', label: 'pesto' },
    { emoji: '🥗', label: 'ranch' },
    { emoji: '🍤', label: 'tartar_sauce' },
    { emoji: '🥢', label: 'teriyaki_sauce' },
    { emoji: '🥢', label: 'hoisin_sauce' },
    { emoji: '🐟', label: 'fish_sauce' },
    { emoji: '🌿', label: 'chimichurri' },
    { emoji: '🍯', label: 'honey' },
    { emoji: '🌶️', label: 'sriracha' },
    { emoji: '🥢', label: 'soy_paste' },
    { emoji: '🍶', label: 'vinegar' },
    { emoji: '🫒', label: 'olive_oil' },
    { emoji: '🥢', label: 'sesame_oil' },
    { emoji: '🍶', label: 'balsamic_vinegar' },
  ],
  fruits: [
    { emoji: '🍎', label: 'apple' },
    { emoji: '🍌', label: 'banana' },
    { emoji: '🍊', label: 'orange' },
    { emoji: '🍓', label: 'strawberry' },
    { emoji: '🫐', label: 'blueberry' },
    { emoji: '🍇', label: 'grape' },
    { emoji: '🍈', label: 'melon' },
    { emoji: '🍍', label: 'pineapple' },
    { emoji: '🥝', label: 'kiwi' },
    { emoji: '🥭', label: 'mango' },
    { emoji: '🍐', label: 'pear' },
    { emoji: '🍑', label: 'peach' },
    { emoji: '🍑', label: 'plum' },
    { emoji: '🍒', label: 'cherry' },
    { emoji: '🍇', label: 'fig' },
    { emoji: '🌴', label: 'date' },
    { emoji: '🍎', label: 'pomegranate' },
    { emoji: '🍑', label: 'apricot' },
    { emoji: '🫐', label: 'blackberry' },
    { emoji: '🫐', label: 'raspberry' },
  ],
  dairy: [
    { emoji: '🥛', label: 'milk' },
    { emoji: '🧀', label: 'cheese' },
    { emoji: '🧈', label: 'butter' },
    { emoji: '🥛', label: 'yogurt' },
    { emoji: '🥛', label: 'cream' },
    { emoji: '🥛', label: 'sour_cream' },
    { emoji: '🧀', label: 'cream_cheese' },
    { emoji: '🍦', label: 'ice_cream' },
    { emoji: '🍦', label: 'whipped_cream' },
    { emoji: '🥛', label: 'condensed_milk' },
    { emoji: '🥛', label: 'evaporated_milk' },
    { emoji: '🧀', label: 'parmesan' },
    { emoji: '🧀', label: 'mozzarella' },
    { emoji: '🧀', label: 'brie' },
    { emoji: '🧀', label: 'cheddar' },
    { emoji: '🧀', label: 'gouda' },
    { emoji: '🧀', label: 'feta' },
    { emoji: '🧀', label: 'blue_cheese' },
    { emoji: '🧀', label: 'swiss_cheese' },
    { emoji: '🧀', label: 'provolone' },
  ],
  grains: [
    { emoji: '🍚', label: 'rice' },
    { emoji: '🍞', label: 'bread' },
    { emoji: '🍝', label: 'pasta' },
    { emoji: '🌾', label: 'oats' },
    { emoji: '🌾', label: 'quinoa' },
    { emoji: '🌾', label: 'barley' },
    { emoji: '🌽', label: 'cornmeal' },
    { emoji: '🌾', label: 'bulgur' },
    { emoji: '🌾', label: 'couscous' },
    { emoji: '🌾', label: 'wheat_flour' },
    { emoji: '🌾', label: 'rye' },
    { emoji: '🌾', label: 'buckwheat' },
    { emoji: '🌾', label: 'sorghum' },
    { emoji: '🌾', label: 'millet' },
    { emoji: '🌾', label: 'amaranth' },
    { emoji: '🌾', label: 'farro' },
    { emoji: '🌾', label: 'spelt' },
    { emoji: '🌾', label: 'teff' },
    { emoji: '🌾', label: 'kamut' },
    { emoji: '🌾', label: 'freekeh' },
  ],
  seafood: [
    { emoji: '🐟', label: 'salmon' },
    { emoji: '🐟', label: 'tuna' },
    { emoji: '🍤', label: 'shrimp' },
    { emoji: '🦀', label: 'crab' },
    { emoji: '🦞', label: 'lobster' },
    { emoji: '🦪', label: 'oyster' },
    { emoji: '🦪', label: 'mussel' },
    { emoji: '🦪', label: 'clam' },
    { emoji: '🦪', label: 'scallop' },
    { emoji: '🐙', label: 'octopus' },
    { emoji: '🦑', label: 'squid' },
    { emoji: '🐟', label: 'anchovy' },
    { emoji: '🐟', label: 'sardine' },
    { emoji: '🐟', label: 'mackerel' },
    { emoji: '🐟', label: 'cod' },
    { emoji: '🐟', label: 'haddock' },
    { emoji: '🐟', label: 'halibut' },
    { emoji: '🐟', label: 'trout' },
    { emoji: '🐟', label: 'snapper' },
    { emoji: '🐟', label: 'sea_bass' },
  ],
};
