export const categories: {
  [key: string]: { emoji: string; items: { emoji: string; label: string }[] };
} = {
  vegetables: {
    emoji: '🥦',
    items: [
      { emoji: '🧅', label: 'onion' },
      { emoji: '🥔', label: 'potato' },
      { emoji: '🥕', label: 'carrot' },
      { emoji: '🥒', label: 'cucumber' },
      { emoji: '🌶️', label: 'pepper' },
      { emoji: '🍅', label: 'tomato' },
      { emoji: '🥦', label: 'broccoli' },
      { emoji: '🥬', label: 'cabbage' },
      { emoji: '🥬', label: 'spinach' },
      { emoji: '🥬', label: 'lettuce' },
      { emoji: '🥒', label: 'zucchini' },
      { emoji: '🍆', label: 'eggplant' },
      { emoji: '🧄', label: 'garlic' },
      { emoji: '🫚', label: 'ginger' },
      { emoji: '🍄', label: 'mushroom' },
      { emoji: '🥦', label: 'cauliflower' },
      { emoji: '🌽', label: 'corn' },
      { emoji: '🟢', label: 'peas' },
      { emoji: '🍠', label: 'sweet_potato' },
      { emoji: '🍠', label: 'beetroot' },
      // Korean specific vegetables
      { emoji: '🥬', label: 'napa_cabbage' },
      { emoji: '🌿', label: 'perilla_leaf' },
      { emoji: '🥬', label: 'korean_chives' },
      { emoji: '🥬', label: 'korean_lettuce' },
      { emoji: '🥕', label: 'radish' },
      { emoji: '🍄', label: 'shiitake_mushroom' },
      { emoji: '🍄', label: 'enoki_mushroom' },
      { emoji: '🍄', label: 'king_oyster_mushroom' },
      { emoji: '🌿', label: 'bean_sprouts' },
      { emoji: '🌿', label: 'korean_mugwort' },
      { emoji: '🌿', label: 'crown_daisy' },
      // Additional Korean vegetables
      { emoji: '🥕', label: 'korean_carrot' },
      { emoji: '🌿', label: 'water_dropwort' },
      { emoji: '🥬', label: 'sesame_leaves' },
      { emoji: '🌿', label: 'chamnamul' },
      { emoji: '🌿', label: 'wild_chives' },
      // Additional vegetables from around the world
      { emoji: '🥒', label: 'okra' },
      { emoji: '🥒', label: 'bitter_melon' },
      { emoji: '🥬', label: 'swiss_chard' },
      { emoji: '🍄', label: 'chanterelle' },
      { emoji: '🍄', label: 'porcini' },
      { emoji: '🍄', label: 'morel' },
      { emoji: '🥬', label: 'arugula' },
      { emoji: '🌽', label: 'baby_corn' },
      { emoji: '🥕', label: 'parsnip' },
      { emoji: '🌿', label: 'dill' },
      { emoji: '🌿', label: 'cilantro' },
      { emoji: '🌶️', label: 'habanero' },
      { emoji: '🌶️', label: 'serrano' },
      { emoji: '🍠', label: 'yucca' },
      { emoji: '🥕', label: 'turnip' },
      { emoji: '🌿', label: 'fennel' },
      { emoji: '🌿', label: 'lemongrass' },
      // Europe, USA, Japan specific vegetables
      { emoji: '🥕', label: 'baby_carrots' },
      { emoji: '🌿', label: 'basil' },
      { emoji: '🍄', label: 'white_button_mushroom' },
      { emoji: '🥬', label: 'romaine_lettuce' },
      { emoji: '🍅', label: 'cherry_tomato' },
      { emoji: '🥦', label: 'asparagus' },
    ],
  },
  meats: {
    emoji: '🍖',
    items: [
      { emoji: '🥩', label: 'beef' },
      { emoji: '🍗', label: 'chicken' },
      { emoji: '🥓', label: 'pork_belly' },
      { emoji: '🍖', label: 'pork_shoulder' },
      { emoji: '🍖', label: 'pork_rib' },
      { emoji: '🍖', label: 'pork_butt' },
      { emoji: '🥩', label: 'ribeye' },
      { emoji: '🥩', label: 'tenderloin' },
      { emoji: '🥩', label: 'brisket' },
      { emoji: '🥩', label: 'sirloin' },
      { emoji: '🥩', label: 'flank_steak' },
      { emoji: '🍖', label: 'short_ribs' },
      { emoji: '🍖', label: 'spare_ribs' },
      { emoji: '🍖', label: 'ham' },
      { emoji: '🌭', label: 'sausage' },
      { emoji: '🍖', label: 'bacon' },
      { emoji: '🦆', label: 'duck' },
      { emoji: '🦃', label: 'turkey' },
      { emoji: '🐐', label: 'goat' },
      { emoji: '🐇', label: 'rabbit' },
      { emoji: '🦌', label: 'venison' },
      { emoji: '🍖', label: 'salami' },
      { emoji: '🍖', label: 'prosciutto' },
      { emoji: '🍖', label: 'chorizo' },
      { emoji: '🍖', label: 'meatballs' },
      { emoji: '🥩', label: 'oxtail' },
      // Additional meats
      { emoji: '🍗', label: 'chicken_breast' },
      { emoji: '🍗', label: 'chicken_thigh' },
      { emoji: '🍗', label: 'chicken_wing' },
      { emoji: '🍖', label: 'lamb' },
      { emoji: '🍗', label: 'chicken_feet' },
      { emoji: '🍖', label: 'galbi' },
      // Additional meats from around the world
      { emoji: '🥩', label: 'veal' },
      { emoji: '🍗', label: 'quail' },
      { emoji: '🍗', label: 'pigeon' },
      { emoji: '🍖', label: 'kielbasa' },
      { emoji: '🍖', label: 'bresaola' },
      { emoji: '🍖', label: 'liver' },
      { emoji: '🍖', label: 'tripe' },
      { emoji: '🍗', label: 'giblets' },
      { emoji: '🍗', label: 'duck_breast' },
      { emoji: '🍗', label: 'pheasant' },
      { emoji: '🍗', label: 'guinea_fowl' },
      { emoji: '🍗', label: 'ostrich' },
      { emoji: '🍗', label: 'emu' },
      { emoji: '🍗', label: 'alligator' },
      // Europe, USA, Japan specific meats
      { emoji: '🥩', label: 'wiener_schnitzel' },
      { emoji: '🍗', label: 'fried_chicken' },
      { emoji: '🍖', label: 'roast_beef' },
    ],
  },
  sauces: {
    emoji: '🥫',
    items: [
      { emoji: '🥢', label: 'soy_sauce' },
      { emoji: '🍅', label: 'ketchup' },
      { emoji: '🌭', label: 'mustard' },
      { emoji: '🥪', label: 'mayonnaise' },
      { emoji: '🍖', label: 'bbq_sauce' },
      { emoji: '🌶️', label: 'hot_sauce' },
      { emoji: '🌿', label: 'pesto' },
      { emoji: '🥗', label: 'ranch' },
      { emoji: '🍤', label: 'tartar_sauce' },
      { emoji: '🥢', label: 'teriyaki_sauce' },
      { emoji: '🥢', label: 'hoisin_sauce' },
      { emoji: '🐟', label: 'fish_sauce' },
      { emoji: '🌿', label: 'chimichurri' },
      { emoji: '🍯', label: 'honey' },
      { emoji: '🌶️', label: 'sriracha' },
      { emoji: '🥢', label: 'soy_paste' },
      { emoji: '🍶', label: 'vinegar' },
      { emoji: '🫒', label: 'olive_oil' },
      { emoji: '🥢', label: 'sesame_oil' },
      { emoji: '🍶', label: 'balsamic_vinegar' },
      // Korean sauces
      { emoji: '🌶️', label: 'gochujang' },
      { emoji: '🥢', label: 'doenjang' },
      { emoji: '🥢', label: 'ssamjang' },
      { emoji: '🥢', label: 'soybean_paste' },
      { emoji: '🥢', label: 'chunjang' },
      { emoji: '🥢', label: 'mirin' },
      { emoji: '🥢', label: 'miso' },
      // Additional Korean sauces
      { emoji: '🥢', label: 'chojang' },
      { emoji: '🥢', label: 'myeolchi_aekjeot' },
      { emoji: '🥢', label: 'ganjang' },
      // Europe, USA, Japan specific sauces
      { emoji: '🥫', label: 'wasabi' },
      { emoji: '🍅', label: 'tomato_paste' },
      { emoji: '🍅', label: 'marinara' },
    ],
  },
  fruits: {
    emoji: '🍎',
    items: [
      { emoji: '🍎', label: 'apple' },
      { emoji: '🍌', label: 'banana' },
      { emoji: '🍊', label: 'orange' },
      { emoji: '🍓', label: 'strawberry' },
      { emoji: '🫐', label: 'blueberry' },
      { emoji: '🍇', label: 'grape' },
      { emoji: '🍈', label: 'melon' },
      { emoji: '🍍', label: 'pineapple' },
      { emoji: '🥝', label: 'kiwi' },
      { emoji: '🥭', label: 'mango' },
      { emoji: '🍐', label: 'pear' },
      { emoji: '🍑', label: 'peach' },
      { emoji: '🍑', label: 'plum' },
      { emoji: '🍒', label: 'cherry' },
      { emoji: '🍇', label: 'fig' },
      { emoji: '🌴', label: 'date' },
      { emoji: '🍎', label: 'pomegranate' },
      { emoji: '🍑', label: 'apricot' },
      { emoji: '🫐', label: 'blackberry' },
      { emoji: '🫐', label: 'raspberry' },
      // Additional fruits
      { emoji: '🍋', label: 'lemon' },
      { emoji: '🍋', label: 'lime' },
      { emoji: '🍉', label: 'watermelon' },
      { emoji: '🍈', label: 'honeydew' },
      { emoji: '🍏', label: 'green_apple' },
      { emoji: '🍊', label: 'tangerine' },
      { emoji: '🍍', label: 'papaya' },
      // Korean specific fruits
      { emoji: '🍏', label: 'asian_pear' },
      { emoji: '🍇', label: 'korean_grape' },
      { emoji: '🍊', label: 'persimmon' },
      { emoji: '🍏', label: 'korean_melon' },
      // Europe, USA, Japan specific fruits
      { emoji: '🍎', label: 'cranberry' },
      { emoji: '🍊', label: 'yuzu' },
      { emoji: '🍉', label: 'cantaloupe' },
      { emoji: '🍊', label: 'blood_orange' },
      { emoji: '🍑', label: 'nectarine' },
    ],
  },
  dairy: {
    emoji: '🧀',
    items: [
      { emoji: '🥛', label: 'milk' },
      { emoji: '🧀', label: 'cheese' },
      { emoji: '🧈', label: 'butter' },
      { emoji: '🥛', label: 'yogurt' },
      { emoji: '🥛', label: 'cream' },
      { emoji: '🥛', label: 'sour_cream' },
      { emoji: '🧀', label: 'cream_cheese' },
      { emoji: '🍦', label: 'ice_cream' },
      { emoji: '🍦', label: 'whipped_cream' },
      { emoji: '🥛', label: 'condensed_milk' },
      { emoji: '🥛', label: 'evaporated_milk' },
      { emoji: '🧀', label: 'parmesan' },
      { emoji: '🧀', label: 'mozzarella' },
      { emoji: '🧀', label: 'brie' },
      { emoji: '🧀', label: 'cheddar' },
      { emoji: '🧀', label: 'gouda' },
      { emoji: '🧀', label: 'feta' },
      { emoji: '🧀', label: 'blue_cheese' },
      { emoji: '🧀', label: 'swiss_cheese' },
      { emoji: '🧀', label: 'provolone' },
      // Additional dairy
      { emoji: '🥛', label: 'buttermilk' },
      { emoji: '🧀', label: 'ricotta' },
      { emoji: '🧀', label: 'cottage_cheese' },
      { emoji: '🥛', label: 'kefir' },
      // Europe, USA, Japan specific dairy
      { emoji: '🧀', label: 'mascarpone' },
      { emoji: '🧀', label: 'camembert' },
      { emoji: '🧀', label: 'gruyere' },
      { emoji: '🧀', label: 'pecorino' },
      { emoji: '🧀', label: 'emmental' },
    ],
  },
  grains: {
    emoji: '🍞',
    items: [
      { emoji: '🍚', label: 'rice' },
      { emoji: '🍞', label: 'bread' },
      { emoji: '🍝', label: 'pasta' },
      { emoji: '🌾', label: 'oats' },
      { emoji: '🌾', label: 'quinoa' },
      { emoji: '🌾', label: 'barley' },
      { emoji: '🌽', label: 'cornmeal' },
      { emoji: '🌾', label: 'bulgur' },
      { emoji: '🌾', label: 'couscous' },
      { emoji: '🌾', label: 'wheat_flour' },
      { emoji: '🌾', label: 'rye' },
      { emoji: '🌾', label: 'buckwheat' },
      { emoji: '🌾', label: 'sorghum' },
      { emoji: '🌾', label: 'millet' },
      { emoji: '🌾', label: 'amaranth' },
      { emoji: '🌾', label: 'farro' },
      { emoji: '🌾', label: 'spelt' },
      { emoji: '🌾', label: 'teff' },
      { emoji: '🌾', label: 'kamut' },
      { emoji: '🌾', label: 'freekeh' },
      // Additional grains
      { emoji: '🌾', label: 'semolina' },
      { emoji: '🌾', label: 'rice_noodles' },
      { emoji: '🌾', label: 'udon_noodles' },
      { emoji: '🌾', label: 'soba_noodles' },
      { emoji: '🌾', label: 'ramen_noodles' },
      // Korean specific grains
      { emoji: '🍚', label: 'sticky_rice' },
      { emoji: '🌾', label: 'barley_tea' },
      { emoji: '🌾', label: 'corn_tea' },
      // Europe, USA, Japan specific grains
      { emoji: '🍞', label: 'baguette' },
      { emoji: '🍞', label: 'brioche' },
      { emoji: '🍞', label: 'sourdough' },
      { emoji: '🍞', label: 'ciabatta' },
      { emoji: '🍞', label: 'pita' },
    ],
  },
  seafood: {
    emoji: '🐟',
    items: [
      { emoji: '🐟', label: 'salmon' },
      { emoji: '🐟', label: 'tuna' },
      { emoji: '🍤', label: 'shrimp' },
      { emoji: '🦀', label: 'crab' },
      { emoji: '🦞', label: 'lobster' },
      { emoji: '🦪', label: 'oyster' },
      { emoji: '🦪', label: 'mussel' },
      { emoji: '🦪', label: 'clam' },
      { emoji: '🦪', label: 'scallop' },
      { emoji: '🐙', label: 'octopus' },
      { emoji: '🦑', label: 'squid' },
      { emoji: '🐟', label: 'anchovy' },
      { emoji: '🐟', label: 'sardine' },
      { emoji: '🐟', label: 'mackerel' },
      { emoji: '🐟', label: 'cod' },
      { emoji: '🐟', label: 'haddock' },
      { emoji: '🐟', label: 'halibut' },
      { emoji: '🐟', label: 'trout' },
      { emoji: '🐟', label: 'snapper' },
      { emoji: '🐟', label: 'sea_bass' },
      // Additional seafood
      { emoji: '🐟', label: 'tilapia' },
      { emoji: '🐟', label: 'swordfish' },
      { emoji: '🐟', label: 'king_crab' },
      { emoji: '🦞', label: 'crayfish' },
      { emoji: '🐟', label: 'grouper' },
      // Korean specific seafood
      { emoji: '🐟', label: 'dried_pollack' },
      { emoji: '🐟', label: 'myeolchi' },
      { emoji: '🐟', label: 'godeungeo' },
      { emoji: '🐟', label: 'galchi' },
      { emoji: '🐟', label: 'hongeo' },
      // Europe, USA, Japan specific seafood
      { emoji: '🐟', label: 'herring' },
      { emoji: '🐟', label: 'eel' },
      { emoji: '🐟', label: 'turbot' },
      { emoji: '🐟', label: 'plaice' },
      { emoji: '🐟', label: 'hoki' },
    ],
  },
};
